
// 64 tilesets generated with spritemateX on 25/05/2024, 12:46:21

// tileset 0, Width : 8, Height : 8, Colour Depth : 2

tileset0:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $28          //  ..X.X...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $7c          //  .XXXXX..
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tileset 1, Width : 8, Height : 8, Colour Depth : 2

tileset1:
.byte $00          //  ........
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $78          //  .XXXX...


// tileset 2, Width : 8, Height : 8, Colour Depth : 2

tileset2:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tileset 3, Width : 8, Height : 8, Colour Depth : 2

tileset3:
.byte $00          //  ........
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $78          //  .XXXX...


// tileset 4, Width : 8, Height : 8, Colour Depth : 2

tileset4:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $78          //  .XXXX...
.byte $40          //  .X......
.byte $40          //  .X......
.byte $7c          //  .XXXXX..


// tileset 5, Width : 8, Height : 8, Colour Depth : 2

tileset5:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $78          //  .XXXX...
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......


// tileset 6, Width : 8, Height : 8, Colour Depth : 2

tileset6:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $4c          //  .X..XX..
.byte $44          //  .X...X..
.byte $3c          //  ..XXXX..


// tileset 7, Width : 8, Height : 8, Colour Depth : 2

tileset7:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $7c          //  .XXXXX..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tileset 8, Width : 8, Height : 8, Colour Depth : 2

tileset8:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $38          //  ..XXX...


// tileset 9, Width : 8, Height : 8, Colour Depth : 2

tileset9:
.byte $00          //  ........
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tileset 10, Width : 8, Height : 8, Colour Depth : 2

tileset10:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $48          //  .X..X...
.byte $50          //  .X.X....
.byte $60          //  .XX.....
.byte $50          //  .X.X....
.byte $48          //  .X..X...
.byte $44          //  .X...X..


// tileset 11, Width : 8, Height : 8, Colour Depth : 2

tileset11:
.byte $00          //  ........
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $7c          //  .XXXXX..


// tileset 12, Width : 8, Height : 8, Colour Depth : 2

tileset12:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $6c          //  .XX.XX..
.byte $54          //  .X.X.X..
.byte $54          //  .X.X.X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tileset 13, Width : 8, Height : 8, Colour Depth : 2

tileset13:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $64          //  .XX..X..
.byte $54          //  .X.X.X..
.byte $4c          //  .X..XX..
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tileset 14, Width : 8, Height : 8, Colour Depth : 2

tileset14:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tileset 15, Width : 8, Height : 8, Colour Depth : 2

tileset15:
.byte $00          //  ........
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $78          //  .XXXX...
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......


// tileset 16, Width : 8, Height : 8, Colour Depth : 2

tileset16:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $54          //  .X.X.X..
.byte $48          //  .X..X...
.byte $34          //  ..XX.X..


// tileset 17, Width : 8, Height : 8, Colour Depth : 2

tileset17:
.byte $00          //  ........
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $78          //  .XXXX...
.byte $50          //  .X.X....
.byte $48          //  .X..X...
.byte $44          //  .X...X..


// tileset 18, Width : 8, Height : 8, Colour Depth : 2

tileset18:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $40          //  .X......
.byte $38          //  ..XXX...
.byte $04          //  .....X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tileset 19, Width : 8, Height : 8, Colour Depth : 2

tileset19:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....


// tileset 20, Width : 8, Height : 8, Colour Depth : 2

tileset20:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tileset 21, Width : 8, Height : 8, Colour Depth : 2

tileset21:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $28          //  ..X.X...
.byte $10          //  ...X....


// tileset 22, Width : 8, Height : 8, Colour Depth : 2

tileset22:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $54          //  .X.X.X..
.byte $54          //  .X.X.X..
.byte $6c          //  .XX.XX..
.byte $44          //  .X...X..


// tileset 23, Width : 8, Height : 8, Colour Depth : 2

tileset23:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $28          //  ..X.X...
.byte $10          //  ...X....
.byte $28          //  ..X.X...
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tileset 24, Width : 8, Height : 8, Colour Depth : 2

tileset24:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $28          //  ..X.X...
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....


// tileset 25, Width : 8, Height : 8, Colour Depth : 2

tileset25:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....
.byte $40          //  .X......
.byte $7c          //  .XXXXX..


// tileset 26, Width : 8, Height : 8, Colour Depth : 2

tileset26:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $4c          //  .X..XX..
.byte $54          //  .X.X.X..
.byte $64          //  .XX..X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tileset 27, Width : 8, Height : 8, Colour Depth : 2

tileset27:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $30          //  ..XX....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $38          //  ..XXX...


// tileset 28, Width : 8, Height : 8, Colour Depth : 2

tileset28:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $04          //  .....X..
.byte $18          //  ...XX...
.byte $20          //  ..X.....
.byte $40          //  .X......
.byte $7c          //  .XXXXX..


// tileset 29, Width : 8, Height : 8, Colour Depth : 2

tileset29:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $18          //  ...XX...
.byte $04          //  .....X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tileset 30, Width : 8, Height : 8, Colour Depth : 2

tileset30:
.byte $00          //  ........
.byte $08          //  ....X...
.byte $18          //  ...XX...
.byte $28          //  ..X.X...
.byte $48          //  .X..X...
.byte $7c          //  .XXXXX..
.byte $08          //  ....X...
.byte $08          //  ....X...


// tileset 31, Width : 8, Height : 8, Colour Depth : 2

tileset31:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $40          //  .X......
.byte $78          //  .XXXX...
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tileset 32, Width : 8, Height : 8, Colour Depth : 2

tileset32:
.byte $00          //  ........
.byte $1c          //  ...XXX..
.byte $20          //  ..X.....
.byte $40          //  .X......
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tileset 33, Width : 8, Height : 8, Colour Depth : 2

tileset33:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....
.byte $20          //  ..X.....
.byte $20          //  ..X.....


// tileset 34, Width : 8, Height : 8, Colour Depth : 2

tileset34:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tileset 35, Width : 8, Height : 8, Colour Depth : 2

tileset35:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $3c          //  ..XXXX..
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $70          //  .XXX....


// tileset 36, Width : 8, Height : 8, Colour Depth : 2

tileset36:
.byte $00          //  ........
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....
.byte $40          //  .X......
.byte $20          //  ..X.....
.byte $10          //  ...X....
.byte $08          //  ....X...


// tileset 37, Width : 8, Height : 8, Colour Depth : 2

tileset37:
.byte $00          //  ........
.byte $20          //  ..X.....
.byte $10          //  ...X....
.byte $08          //  ....X...
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....


// tileset 38, Width : 8, Height : 8, Colour Depth : 2

tileset38:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// tileset 39, Width : 8, Height : 8, Colour Depth : 2

tileset39:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $00          //  ........
.byte $00          //  ........


// tileset 40, Width : 8, Height : 8, Colour Depth : 2

tileset40:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $54          //  .X.X.X..
.byte $38          //  ..XXX...
.byte $10          //  ...X....
.byte $38          //  ..XXX...
.byte $54          //  .X.X.X..
.byte $10          //  ...X....


// tileset 41, Width : 8, Height : 8, Colour Depth : 2

tileset41:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $28          //  ..X.X...
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tileset 42, Width : 8, Height : 8, Colour Depth : 2

tileset42:
.byte $01          //  .......X
.byte $03          //  ......XX
.byte $07          //  .....XXX
.byte $0d          //  ....XX.X
.byte $0f          //  ....XXXX
.byte $02          //  ......X.
.byte $05          //  .....X.X
.byte $0a          //  ....X.X.


// tileset 43, Width : 8, Height : 8, Colour Depth : 2

tileset43:
.byte $80          //  X.......
.byte $c0          //  XX......
.byte $e0          //  XXX.....
.byte $b0          //  X.XX....
.byte $f0          //  XXXX....
.byte $40          //  .X......
.byte $a0          //  X.X.....
.byte $50          //  .X.X....


// tileset 44, Width : 8, Height : 8, Colour Depth : 2

tileset44:
.byte $08          //  ....X...
.byte $24          //  ..X..X..
.byte $2f          //  ..X.XXXX
.byte $3b          //  ..XXX.XX
.byte $3f          //  ..XXXXXX
.byte $1f          //  ...XXXXX
.byte $08          //  ....X...
.byte $10          //  ...X....


// tileset 45, Width : 8, Height : 8, Colour Depth : 2

tileset45:
.byte $20          //  ..X.....
.byte $48          //  .X..X...
.byte $e8          //  XXX.X...
.byte $b8          //  X.XXX...
.byte $f8          //  XXXXX...
.byte $f0          //  XXXX....
.byte $20          //  ..X.....
.byte $10          //  ...X....


// tileset 46, Width : 8, Height : 8, Colour Depth : 2

tileset46:
.byte $03          //  ......XX
.byte $1f          //  ...XXXXX
.byte $3f          //  ..XXXXXX
.byte $39          //  ..XXX..X
.byte $3f          //  ..XXXXXX
.byte $06          //  .....XX.
.byte $0d          //  ....XX.X
.byte $30          //  ..XX....


// tileset 47, Width : 8, Height : 8, Colour Depth : 2

tileset47:
.byte $c0          //  XX......
.byte $f8          //  XXXXX...
.byte $fc          //  XXXXXX..
.byte $9c          //  X..XXX..
.byte $fc          //  XXXXXX..
.byte $60          //  .XX.....
.byte $b0          //  X.XX....
.byte $0c          //  ....XX..


// tileset 48, Width : 8, Height : 8, Colour Depth : 2

tileset48:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $1d          //  ...XXX.X
.byte $13          //  ...X..XX
.byte $28          //  ..X.X...
.byte $45          //  .X...X.X
.byte $44          //  .X...X..


// tileset 49, Width : 8, Height : 8, Colour Depth : 2

tileset49:
.byte $30          //  ..XX....
.byte $78          //  .XXXX...
.byte $fc          //  XXXXXX..
.byte $b6          //  X.XX.XX.
.byte $fe          //  XXXXXXX.
.byte $b4          //  X.XX.X..
.byte $02          //  ......X.
.byte $84          //  X....X..


// tileset 50, Width : 8, Height : 8, Colour Depth : 2

tileset50:
.byte $00          //  ........
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $0d          //  ....XX.X
.byte $0b          //  ....X.XX
.byte $14          //  ...X.X..
.byte $22          //  ..X...X.
.byte $23          //  ..X...XX


// tileset 51, Width : 8, Height : 8, Colour Depth : 2

tileset51:
.byte $30          //  ..XX....
.byte $78          //  .XXXX...
.byte $fc          //  XXXXXX..
.byte $b6          //  X.XX.XX.
.byte $fe          //  XXXXXXX.
.byte $48          //  .X..X...
.byte $b4          //  X.XX.X..
.byte $4a          //  .X..X.X.


// tileset 52, Width : 8, Height : 8, Colour Depth : 2

tileset52:
.byte $00          //  ........
.byte $07          //  .....XXX
.byte $1f          //  ...XXXXX
.byte $3f          //  ..XXXXXX
.byte $6d          //  .XX.XX.X
.byte $ff          //  XXXXXXXX
.byte $39          //  ..XXX..X
.byte $10          //  ...X....


// tileset 53, Width : 8, Height : 8, Colour Depth : 2

tileset53:
.byte $00          //  ........
.byte $e0          //  XXX.....
.byte $f8          //  XXXXX...
.byte $fc          //  XXXXXX..
.byte $b6          //  X.XX.XX.
.byte $ff          //  XXXXXXXX
.byte $9c          //  X..XXX..
.byte $08          //  ....X...


// tileset 54, Width : 8, Height : 8, Colour Depth : 2

tileset54:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// tileset 55, Width : 8, Height : 8, Colour Depth : 2

tileset55:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// tileset 56, Width : 8, Height : 8, Colour Depth : 2

tileset56:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $00          //  ........
.byte $10          //  ...X....


// tileset 57, Width : 8, Height : 8, Colour Depth : 2

tileset57:
.byte $00          //  ........
.byte $01          //  .......X
.byte $01          //  .......X
.byte $1f          //  ...XXXXX
.byte $3f          //  ..XXXXXX
.byte $3f          //  ..XXXXXX
.byte $3f          //  ..XXXXXX
.byte $3f          //  ..XXXXXX


// tileset 58, Width : 8, Height : 8, Colour Depth : 2

tileset58:
.byte $80          //  X.......
.byte $c0          //  XX......
.byte $c0          //  XX......
.byte $fc          //  XXXXXX..
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.


// tileset 59, Width : 8, Height : 8, Colour Depth : 2

tileset59:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// tileset 60, Width : 8, Height : 8, Colour Depth : 2

tileset60:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// tileset 61, Width : 8, Height : 8, Colour Depth : 2

tileset61:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $aa          //  X.X.X.X.


// tileset 62, Width : 8, Height : 8, Colour Depth : 2

tileset62:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $ff          //  XXXXXXXX


// tileset 63, Width : 8, Height : 8, Colour Depth : 2

tileset63:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


tilesetColourPallet:
.byte $00, $00
.byte $ff, $0f