
// 64 tiles generated with tilemateX on 25/05/2024, 23:36:28

// tile 0, Width : 8, Height : 8, Colour Depth : 2

tile0:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $28          //  ..X.X...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $7c          //  .XXXXX..
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tile 1, Width : 8, Height : 8, Colour Depth : 2

tile1:
.byte $00          //  ........
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $78          //  .XXXX...


// tile 2, Width : 8, Height : 8, Colour Depth : 2

tile2:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tile 3, Width : 8, Height : 8, Colour Depth : 2

tile3:
.byte $00          //  ........
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $78          //  .XXXX...


// tile 4, Width : 8, Height : 8, Colour Depth : 2

tile4:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $78          //  .XXXX...
.byte $40          //  .X......
.byte $40          //  .X......
.byte $7c          //  .XXXXX..


// tile 5, Width : 8, Height : 8, Colour Depth : 2

tile5:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $78          //  .XXXX...
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......


// tile 6, Width : 8, Height : 8, Colour Depth : 2

tile6:
.byte $00          //  ........
.byte $3c          //  ..XXXX..
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $4c          //  .X..XX..
.byte $44          //  .X...X..
.byte $3c          //  ..XXXX..


// tile 7, Width : 8, Height : 8, Colour Depth : 2

tile7:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $7c          //  .XXXXX..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tile 8, Width : 8, Height : 8, Colour Depth : 2

tile8:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $38          //  ..XXX...


// tile 9, Width : 8, Height : 8, Colour Depth : 2

tile9:
.byte $00          //  ........
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tile 10, Width : 8, Height : 8, Colour Depth : 2

tile10:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $48          //  .X..X...
.byte $50          //  .X.X....
.byte $60          //  .XX.....
.byte $50          //  .X.X....
.byte $48          //  .X..X...
.byte $44          //  .X...X..


// tile 11, Width : 8, Height : 8, Colour Depth : 2

tile11:
.byte $00          //  ........
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......
.byte $7c          //  .XXXXX..


// tile 12, Width : 8, Height : 8, Colour Depth : 2

tile12:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $6c          //  .XX.XX..
.byte $54          //  .X.X.X..
.byte $54          //  .X.X.X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tile 13, Width : 8, Height : 8, Colour Depth : 2

tile13:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $64          //  .XX..X..
.byte $54          //  .X.X.X..
.byte $4c          //  .X..XX..
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tile 14, Width : 8, Height : 8, Colour Depth : 2

tile14:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tile 15, Width : 8, Height : 8, Colour Depth : 2

tile15:
.byte $00          //  ........
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $78          //  .XXXX...
.byte $40          //  .X......
.byte $40          //  .X......
.byte $40          //  .X......


// tile 16, Width : 8, Height : 8, Colour Depth : 2

tile16:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $54          //  .X.X.X..
.byte $48          //  .X..X...
.byte $34          //  ..XX.X..


// tile 17, Width : 8, Height : 8, Colour Depth : 2

tile17:
.byte $00          //  ........
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $78          //  .XXXX...
.byte $50          //  .X.X....
.byte $48          //  .X..X...
.byte $44          //  .X...X..


// tile 18, Width : 8, Height : 8, Colour Depth : 2

tile18:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $40          //  .X......
.byte $38          //  ..XXX...
.byte $04          //  .....X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tile 19, Width : 8, Height : 8, Colour Depth : 2

tile19:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....


// tile 20, Width : 8, Height : 8, Colour Depth : 2

tile20:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tile 21, Width : 8, Height : 8, Colour Depth : 2

tile21:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $28          //  ..X.X...
.byte $10          //  ...X....


// tile 22, Width : 8, Height : 8, Colour Depth : 2

tile22:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $54          //  .X.X.X..
.byte $54          //  .X.X.X..
.byte $6c          //  .XX.XX..
.byte $44          //  .X...X..


// tile 23, Width : 8, Height : 8, Colour Depth : 2

tile23:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $28          //  ..X.X...
.byte $10          //  ...X....
.byte $28          //  ..X.X...
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tile 24, Width : 8, Height : 8, Colour Depth : 2

tile24:
.byte $00          //  ........
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $28          //  ..X.X...
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....


// tile 25, Width : 8, Height : 8, Colour Depth : 2

tile25:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....
.byte $40          //  .X......
.byte $7c          //  .XXXXX..


// tile 26, Width : 8, Height : 8, Colour Depth : 2

tile26:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $4c          //  .X..XX..
.byte $54          //  .X.X.X..
.byte $64          //  .XX..X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tile 27, Width : 8, Height : 8, Colour Depth : 2

tile27:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $30          //  ..XX....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $38          //  ..XXX...


// tile 28, Width : 8, Height : 8, Colour Depth : 2

tile28:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $04          //  .....X..
.byte $18          //  ...XX...
.byte $20          //  ..X.....
.byte $40          //  .X......
.byte $7c          //  .XXXXX..


// tile 29, Width : 8, Height : 8, Colour Depth : 2

tile29:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $18          //  ...XX...
.byte $04          //  .....X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tile 30, Width : 8, Height : 8, Colour Depth : 2

tile30:
.byte $00          //  ........
.byte $08          //  ....X...
.byte $18          //  ...XX...
.byte $28          //  ..X.X...
.byte $48          //  .X..X...
.byte $7c          //  .XXXXX..
.byte $08          //  ....X...
.byte $08          //  ....X...


// tile 31, Width : 8, Height : 8, Colour Depth : 2

tile31:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $40          //  .X......
.byte $78          //  .XXXX...
.byte $04          //  .....X..
.byte $04          //  .....X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tile 32, Width : 8, Height : 8, Colour Depth : 2

tile32:
.byte $00          //  ........
.byte $1c          //  ...XXX..
.byte $20          //  ..X.....
.byte $40          //  .X......
.byte $78          //  .XXXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tile 33, Width : 8, Height : 8, Colour Depth : 2

tile33:
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....
.byte $20          //  ..X.....
.byte $20          //  ..X.....


// tile 34, Width : 8, Height : 8, Colour Depth : 2

tile34:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $38          //  ..XXX...


// tile 35, Width : 8, Height : 8, Colour Depth : 2

tile35:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $44          //  .X...X..
.byte $3c          //  ..XXXX..
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $70          //  .XXX....


// tile 36, Width : 8, Height : 8, Colour Depth : 2

tile36:
.byte $00          //  ........
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....
.byte $40          //  .X......
.byte $20          //  ..X.....
.byte $10          //  ...X....
.byte $08          //  ....X...


// tile 37, Width : 8, Height : 8, Colour Depth : 2

tile37:
.byte $00          //  ........
.byte $20          //  ..X.....
.byte $10          //  ...X....
.byte $08          //  ....X...
.byte $04          //  .....X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $20          //  ..X.....


// tile 38, Width : 8, Height : 8, Colour Depth : 2

tile38:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// tile 39, Width : 8, Height : 8, Colour Depth : 2

tile39:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $00          //  ........
.byte $00          //  ........


// tile 40, Width : 8, Height : 8, Colour Depth : 2

tile40:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $54          //  .X.X.X..
.byte $38          //  ..XXX...
.byte $10          //  ...X....
.byte $38          //  ..XXX...
.byte $54          //  .X.X.X..
.byte $10          //  ...X....


// tile 41, Width : 8, Height : 8, Colour Depth : 2

tile41:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $28          //  ..X.X...
.byte $44          //  .X...X..
.byte $44          //  .X...X..


// tile 42, Width : 8, Height : 8, Colour Depth : 2

tile42:
.byte $01          //  .......X
.byte $03          //  ......XX
.byte $07          //  .....XXX
.byte $0d          //  ....XX.X
.byte $0f          //  ....XXXX
.byte $02          //  ......X.
.byte $05          //  .....X.X
.byte $0a          //  ....X.X.


// tile 43, Width : 8, Height : 8, Colour Depth : 2

tile43:
.byte $80          //  X.......
.byte $c0          //  XX......
.byte $e0          //  XXX.....
.byte $b0          //  X.XX....
.byte $f0          //  XXXX....
.byte $40          //  .X......
.byte $a0          //  X.X.....
.byte $50          //  .X.X....


// tile 44, Width : 8, Height : 8, Colour Depth : 2

tile44:
.byte $08          //  ....X...
.byte $04          //  .....X..
.byte $0f          //  ....XXXX
.byte $1b          //  ...XX.XX
.byte $3f          //  ..XXXXXX
.byte $2f          //  ..X.XXXX
.byte $28          //  ..X.X...
.byte $06          //  .....XX.


// tile 45, Width : 8, Height : 8, Colour Depth : 2

tile45:
.byte $20          //  ..X.....
.byte $40          //  .X......
.byte $e0          //  XXX.....
.byte $b0          //  X.XX....
.byte $f8          //  XXXXX...
.byte $e8          //  XXX.X...
.byte $28          //  ..X.X...
.byte $c0          //  XX......


// tile 46, Width : 8, Height : 8, Colour Depth : 2

tile46:
.byte $03          //  ......XX
.byte $1f          //  ...XXXXX
.byte $3f          //  ..XXXXXX
.byte $39          //  ..XXX..X
.byte $3f          //  ..XXXXXX
.byte $06          //  .....XX.
.byte $0d          //  ....XX.X
.byte $30          //  ..XX....


// tile 47, Width : 8, Height : 8, Colour Depth : 2

tile47:
.byte $c0          //  XX......
.byte $f8          //  XXXXX...
.byte $fc          //  XXXXXX..
.byte $9c          //  X..XXX..
.byte $fc          //  XXXXXX..
.byte $60          //  .XX.....
.byte $b0          //  X.XX....
.byte $0c          //  ....XX..


// tile 48, Width : 8, Height : 8, Colour Depth : 2

tile48:
.byte $00          //  ........
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $1d          //  ...XXX.X
.byte $13          //  ...X..XX
.byte $28          //  ..X.X...
.byte $45          //  .X...X.X
.byte $44          //  .X...X..


// tile 49, Width : 8, Height : 8, Colour Depth : 2

tile49:
.byte $30          //  ..XX....
.byte $78          //  .XXXX...
.byte $fc          //  XXXXXX..
.byte $b6          //  X.XX.XX.
.byte $fe          //  XXXXXXX.
.byte $b4          //  X.XX.X..
.byte $02          //  ......X.
.byte $84          //  X....X..


// tile 50, Width : 8, Height : 8, Colour Depth : 2

tile50:
.byte $00          //  ........
.byte $08          //  ....X...
.byte $08          //  ....X...
.byte $0d          //  ....XX.X
.byte $0b          //  ....X.XX
.byte $14          //  ...X.X..
.byte $22          //  ..X...X.
.byte $23          //  ..X...XX


// tile 51, Width : 8, Height : 8, Colour Depth : 2

tile51:
.byte $30          //  ..XX....
.byte $78          //  .XXXX...
.byte $fc          //  XXXXXX..
.byte $b6          //  X.XX.XX.
.byte $fe          //  XXXXXXX.
.byte $48          //  .X..X...
.byte $b4          //  X.XX.X..
.byte $4a          //  .X..X.X.


// tile 52, Width : 8, Height : 8, Colour Depth : 2

tile52:
.byte $00          //  ........
.byte $07          //  .....XXX
.byte $1f          //  ...XXXXX
.byte $3f          //  ..XXXXXX
.byte $6d          //  .XX.XX.X
.byte $ff          //  XXXXXXXX
.byte $39          //  ..XXX..X
.byte $10          //  ...X....


// tile 53, Width : 8, Height : 8, Colour Depth : 2

tile53:
.byte $00          //  ........
.byte $e0          //  XXX.....
.byte $f8          //  XXXXX...
.byte $fc          //  XXXXXX..
.byte $b6          //  X.XX.XX.
.byte $ff          //  XXXXXXXX
.byte $9c          //  X..XXX..
.byte $08          //  ....X...


// tile 54, Width : 8, Height : 8, Colour Depth : 2

tile54:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// tile 55, Width : 8, Height : 8, Colour Depth : 2

tile55:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// tile 56, Width : 8, Height : 8, Colour Depth : 2

tile56:
.byte $00          //  ........
.byte $38          //  ..XXX...
.byte $44          //  .X...X..
.byte $08          //  ....X...
.byte $10          //  ...X....
.byte $10          //  ...X....
.byte $00          //  ........
.byte $10          //  ...X....


// tile 57, Width : 8, Height : 8, Colour Depth : 2

tile57:
.byte $00          //  ........
.byte $01          //  .......X
.byte $01          //  .......X
.byte $1f          //  ...XXXXX
.byte $3f          //  ..XXXXXX
.byte $3f          //  ..XXXXXX
.byte $3f          //  ..XXXXXX
.byte $3f          //  ..XXXXXX


// tile 58, Width : 8, Height : 8, Colour Depth : 2

tile58:
.byte $80          //  X.......
.byte $c0          //  XX......
.byte $c0          //  XX......
.byte $fc          //  XXXXXX..
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.
.byte $fe          //  XXXXXXX.


// tile 59, Width : 8, Height : 8, Colour Depth : 2

tile59:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// tile 60, Width : 8, Height : 8, Colour Depth : 2

tile60:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


// tile 61, Width : 8, Height : 8, Colour Depth : 2

tile61:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $aa          //  X.X.X.X.


// tile 62, Width : 8, Height : 8, Colour Depth : 2

tile62:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $ff          //  XXXXXXXX


// tile 63, Width : 8, Height : 8, Colour Depth : 2

tile63:
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........
.byte $7c          //  .XXXXX..
.byte $00          //  ........
.byte $00          //  ........
.byte $00          //  ........


tileColourPallet:
.byte $00, $00
.byte $ff, $0f